/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/girls/': RouteRecordInfo<
      '/girls/',
      '/girls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/「言葉はまるで雪の結晶。」': RouteRecordInfo<
      '/posts/「言葉はまるで雪の結晶。」',
      '/posts/%E3%80%8C%E8%A8%80%E8%91%89%E3%81%AF%E3%81%BE%E3%82%8B%E3%81%A7%E9%9B%AA%E3%81%AE%E7%B5%90%E6%99%B6%E3%80%82%E3%80%8D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/从壹开始的博客生活': RouteRecordInfo<
      '/posts/从壹开始的博客生活',
      '/posts/%E4%BB%8E%E5%A3%B9%E5%BC%80%E5%A7%8B%E7%9A%84%E5%8D%9A%E5%AE%A2%E7%94%9F%E6%B4%BB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/从零开始的博客生活': RouteRecordInfo<
      '/posts/从零开始的博客生活',
      '/posts/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E7%9A%84%E5%8D%9A%E5%AE%A2%E7%94%9F%E6%B4%BB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/我的人生哲学': RouteRecordInfo<
      '/posts/我的人生哲学',
      '/posts/%E6%88%91%E7%9A%84%E4%BA%BA%E7%94%9F%E5%93%B2%E5%AD%A6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/我的学习生涯': RouteRecordInfo<
      '/posts/我的学习生涯',
      '/posts/%E6%88%91%E7%9A%84%E5%AD%A6%E4%B9%A0%E7%94%9F%E6%B6%AF',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/执业医师 医師免許証 Notes': RouteRecordInfo<
      '/posts/执业医师 医師免許証 Notes',
      '/posts/%E6%89%A7%E4%B8%9A%E5%8C%BB%E5%B8%88%20%E5%8C%BB%E5%B8%AB%E5%85%8D%E8%A8%B1%E8%A8%BC%20Notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/24年': RouteRecordInfo<
      '/posts/24年',
      '/posts/24%E5%B9%B4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/JLPT N1 Notes': RouteRecordInfo<
      '/posts/JLPT N1 Notes',
      '/posts/JLPT%20N1%20Notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/LIVE PROJECT': RouteRecordInfo<
      '/posts/LIVE PROJECT',
      '/posts/LIVE%20PROJECT',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/TOEFL Notes': RouteRecordInfo<
      '/posts/TOEFL Notes',
      '/posts/TOEFL%20Notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.27_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.27.0_@babel+parser_5492811e4b7609765b729a963bd24e0a/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/girls/index.md': {
      routes:
        | '/girls/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.27_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.27_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/「言葉はまるで雪の結晶。」.md': {
      routes:
        | '/posts/「言葉はまるで雪の結晶。」'
      views:
        | never
    }
    'pages/posts/从壹开始的博客生活.md': {
      routes:
        | '/posts/从壹开始的博客生活'
      views:
        | never
    }
    'pages/posts/从零开始的博客生活.md': {
      routes:
        | '/posts/从零开始的博客生活'
      views:
        | never
    }
    'pages/posts/我的人生哲学.md': {
      routes:
        | '/posts/我的人生哲学'
      views:
        | never
    }
    'pages/posts/我的学习生涯.md': {
      routes:
        | '/posts/我的学习生涯'
      views:
        | never
    }
    'pages/posts/执业医师 医師免許証 Notes.md': {
      routes:
        | '/posts/执业医师 医師免許証 Notes'
      views:
        | never
    }
    'pages/posts/24年.md': {
      routes:
        | '/posts/24年'
      views:
        | never
    }
    'pages/posts/JLPT N1 Notes.md': {
      routes:
        | '/posts/JLPT N1 Notes'
      views:
        | never
    }
    'pages/posts/LIVE PROJECT.md': {
      routes:
        | '/posts/LIVE PROJECT'
      views:
        | never
    }
    'pages/posts/TOEFL Notes.md': {
      routes:
        | '/posts/TOEFL Notes'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
